clone:
  path: bonno
build:
  image: golang:1.6
  commands:
    - go get github.com/revel/revel
    - go get github.com/revel/cmd/revel
    - go get gopkg.in/gorp.v1
    - go get github.com/mattn/go-sqlite3
    - revel test bonno

