language: go
go:
  - master
install:
    - sudo apt-get update
    - sudo apt-get install -y sqlite3 libsqlite3-dev
    - go get github.com/revel/revel
    - go get github.com/revel/cmd/revel 
    - go get gopkg.in/gorp.v1 
    - go get github.com/mattn/go-sqlite3
script: 
    - cd $GOPATH/src
    - git clone https://github.com/bandoshintaro/bonno
    - revel test bonno
