apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bonno
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bonno
        tier: frontend
    spec:
      containers:
      - name: bonno
        image: bando/bonno
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
        env:
        - name: DB_DRIVER
          value: sqlite3
        - name: TZ
          value: Asia/Tokyo
        - name: DB_DIRECTORY
          value: /go/src/bonno/db/app.db
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /go/src/bonno/db
          name: data
        volumeMounts:
        - mountPath: /go/src/bonno/public/douga
          name: movie
      volumes:
      - name: data
        emptyDir: {}
      - name: movie
        hostPath:
           path: /mnt/sdd2

---

apiVersion: v1
kind: Service
metadata:
  name: bonno
  labels:
    app: bonno
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30202
  selector:
    app: bonno
    tier: frontend

