version: '2'

services:
    bonno:
        environment:
            DB_DRIVER: sqlite3
            DB_DIRECTORY: /go/src/bonno/conf/app.db
        volumes:
          - ./conf:/go/src/bonno/conf
          - ./public/douga:/go/src/bonno/public/douga
        ports:
          - 80:9000
