version: '2'

services:
    bonno:
       build: ./
       restart: always
       ports:
           - 80:9000
       environment:
           DB_DRIVER: sqlite3
           DB_DIRECTORY: /bonno/app.db
       volumes:
           - ./conf:/go/src/bonno/conf
           - ./public/douga:/go/src/bonno/public/douga


